1.

SELECT OH.ORDER_ID,OI.ORDER_ITEM_SEQ_ID,P.PRODUCT_ID,P.PRODUCT_TYPE_ID,OH.SALES_CHANNEL_ENUM_ID ,OH.ORDER_DATE,OH.ENTRY_DATE, OS.STATUS_ID,OS.STATUS_DATETIME ,OH.ORDER_TYPE_ID,OH.PRODUCT_STORE_ID FROM ORDER_HEADER AS OH
JOIN ORDER_ITEM AS OI ON OI.ORDER_ID=OH.ORDER_ID
JOIN ORDER_STATUS AS OS ON OS.ORDER_ID=OH.ORDER_ID
JOIN PRODUCT AS P ON P.PRODUCT_ID=OI.PRODUCT_ID
JOIN PRODUCT_TYPE AS PT ON PT.PRODUCT_TYPE_ID=P.PRODUCT_TYPE_ID
WHERE PT.IS_PHYSICAL='Y'

2.

SELECT RI.RETURN_ID,RI.ORDER_ID,OH.PRODUCT_STORE_ID ,RS.STATUS_DATETIME ,OH.ORDER_NAME,RH.FROM_PARTY_ID ,RH.RETURN_DATE ,RH.ENTRY_DATE ,RH.RETURN_CHANNEL_ENUM_ID
FROM RETURN_ITEM RI 
LEFT JOIN  ORDER_HEADER AS OH ON OH.ORDER_ID =RI.ORDER_ID
LEFT JOIN  RETURN_STATUS AS RS ON RS.RETURN_ID =RI.RETURN_ID
LEFT JOIN RETURN_HEADER AS RH ON RH.RETURN_ID =RI.RETURN_ID
WHERE RS.STATUS_ID ='RETURN_COMPLETED';

3.

4.

5.

SELECT RI.RETURN_ID,RH.ENTRY_DATE,RA.RETURN_ADJUSTMENT_TYPE_ID,RA.AMOUNT,RA.COMMENTS,RI.ORDER_ID,OH.ORDER_DATE,RH.RETURN_DATE,OH.PRODUCT_STORE_ID FROM RETURN_ITEM AS RI
JOIN RETURN_ADJUSTMENT AS RA ON RA.RETURN_ID=RI.RETURN_ID
JOIN ORDER_HEADER AS OH ON OH.ORDER_ID=RI.ORDER_ID
JOIN RETURN_HEADER AS RH ON RH.RETURN_ID=RI.RETURN_ID

6.

SELECT RI.ORDER_ID,RI.RETURN_ID,RH.RETURN_DATE,RR.DESCRIPTION AS RETURN_REASON, RI.RETURN_QUANTITY FROM RETURN_ITEM AS RI
JOIN RETURN_HEADER AS RH ON RH.RETURN_ID=RI.RETURN_ID
JOIN RETURN_REASON AS RR ON RR.RETURN_REASON_ID=RI.RETURN_REASON_ID



7.

SELECT F.FACILITY_ID, F.FACILITY_NAME,COUNT(DISTINCT OH.ORDER_ID) AS TOTAL_ONE_DAY_SHIP_ORDERS  FROM  ORDER_HEADER AS OH
JOIN  ORDER_ITEM_SHIP_GROUP AS OISG ON OH.ORDER_ID = OISG.ORDER_ID
JOIN  FACILITY AS F ON OISG.FACILITY_ID = F.FACILITY_ID
GROUP BY  OISG.FACILITY_ID
ORDER BY TOTAL_ONE_DAY_SHIP_ORDERS DESC LIMIT 1



8.

SELECT   PR.PARTY_ID,PE.FIRST_NAME AS NAME ,PR.ROLE_TYPE_ID,P.FACILITY_ID,PP.STATUS_ID FROM PICKLIST_ROLE AS PR
JOIN PICKLIST AS P ON P.PICKLIST_ID=PR.PICKLIST_ID
JOIN PARTY AS PP ON PP.PARTY_ID=PR.PARTY_ID
JOIN PERSON AS PE ON PE.PARTY_ID=PR.PARTY_ID

9.

SELECT   PF.PRODUCT_ID, P.INTERNAL_NAME,COUNT(PF.FACILITY_ID) AS FACILITY_COUNT FROM PRODUCT_FACILITY AS PF
JOIN PRODUCT AS P ON PF.PRODUCT_ID=P.PRODUCT_ID
GROUP BY PF.FACILITY_ID

10.

SELECT PF.PRODUCT_ID,PF.FACILITY_ID,F.FACILITY_TYPE_ID,II.QUANTITY_ON_HAND_TOTAL AS QOH ,II.AVAILABLE_TO_PROMISE_TOTAL AS ATP FROM PRODUCT_FACILITY AS PF
JOIN FACILITY AS F ON F.FACILITY_ID=PF.FACILITY_ID
JOIN INVENTORY_ITEM AS II ON II.PRODUCT_ID=PF.PRODUCT_ID


11.

12.
